import notes from './notes'

export default {
  Amaj: [notes['A4'], notes['C#5'], notes['E5']],
  Amin: [notes['A4'], notes['C5'], notes['E5']],
  Adim: [notes['A4'], notes['C5'], notes['Eb5']],
  Aaug: [notes['A4'], notes['C#5'], notes['F5']],
  Amaj7: [notes['A4'], notes['C#5'], notes['E5'], notes['G#5']],
  Amin7: [notes['A4'], notes['C5'], notes['E5'], notes['G5']],
  A7: [notes['A4'], notes['C#5'], notes['E5'], notes['G5']],
  A7sus4: [notes['A4'], notes['D5'], notes['E5'], notes['G5']],
  A6: [notes['A4'], notes['C#5'], notes['E5'], notes['F#5']],
  A9: [notes['A4'], notes['C#5'], notes['E5'], notes['G5'], notes['B5']],
  Amin9: [notes['A4'], notes['C5'], notes['E5'], notes['G5'], notes['B5']],
  A11: [
    notes['A4'],
    notes['C#5'],
    notes['E5'],
    notes['G5'],
    notes['B5'],
    notes['D6']
  ],
  A13: [
    notes['A4'],
    notes['C#5'],
    notes['E5'],
    notes['G5'],
    notes['B5'],
    notes['D6'],
    notes['F#6']
  ],

  Bbmaj: [notes['Bb4'], notes['D5'], notes['F5']],
  Bbmin: [notes['Bb4'], notes['Db5'], notes['F5']],
  Bbdim: [notes['Bb4'], notes['Db5'], notes['E5']],
  Bbaug: [notes['Bb4'], notes['D5'], notes['F#5']],
  Bbmaj7: [notes['Bb4'], notes['D5'], notes['F5'], notes['A5']],
  Bbmin7: [notes['Bb4'], notes['Db5'], notes['F5'], notes['Ab5']],
  Bb7: [notes['Bb4'], notes['D5'], notes['F5'], notes['Ab5']],
  Bb7sus4: [notes['Bb4'], notes['Eb5'], notes['F5'], notes['Ab5']],

  Bmaj: [notes['B4'], notes['D#5'], notes['F#5']],
  Bmin: [notes['B4'], notes['D5'], notes['F#5']],
  Bdim: [notes['B4'], notes['D5'], notes['F5']],
  Baug: [notes['B4'], notes['D#5'], notes['G5']],
  Bmaj7: [notes['B4'], notes['D#5'], notes['F#5'], notes['A#5']],
  Bmin7: [notes['B4'], notes['D5'], notes['F#5'], notes['A5']],
  B7: [notes['B4'], notes['D#5'], notes['F#5'], notes['A5']],
  B7sus4: [notes['B4'], notes['E5'], notes['F#5'], notes['A5']],

  Cmaj: [notes['C4'], notes['E4'], notes['G4']],
  Cmin: [notes['C4'], notes['Eb4'], notes['G4']],
  Cdim: [notes['C4'], notes['Eb4'], notes['Gb4']],
  Caug: [notes['C4'], notes['E4'], notes['G#4']],
  Cmaj7: [notes['C4'], notes['E4'], notes['G4'], notes['B4']],
  Cmin7: [notes['C4'], notes['Eb4'], notes['G4'], notes['Bb4']],
  C7: [notes['C4'], notes['E4'], notes['G4'], notes['Bb4']],
  C7sus4: [notes['C4'], notes['F4'], notes['G4'], notes['Bb4']],

  Dbmaj: [notes['Db4'], notes['F4'], notes['Ab4']],
  Dbmin: [notes['Db4'], notes['E4'], notes['Ab4']],
  Dbdim: [notes['Db4'], notes['E4'], notes['G4']],
  Dbaug: [notes['Db4'], notes['F4'], notes['A4']],
  Dbmaj7: [notes['Db4'], notes['F4'], notes['Ab4'], notes['C5']],
  Dbmin7: [notes['Db4'], notes['E4'], notes['Ab4'], notes['B4']],
  Db7: [notes['Db4'], notes['F4'], notes['Ab4'], notes['B4']],
  Db7sus4: [notes['Db4'], notes['Gb4'], notes['Ab4'], notes['B4']],

  Dmaj: [notes['D4'], notes['F#4'], notes['A4']],
  Dmin: [notes['D4'], notes['F4'], notes['A4']],
  Ddim: [notes['D4'], notes['F4'], notes['Ab4']],
  Daug: [notes['D4'], notes['F#4'], notes['A#4']],
  Dmaj7: [notes['D4'], notes['F#4'], notes['A4'], notes['C#5']],
  Dmin7: [notes['D4'], notes['F4'], notes['A4'], notes['C5']],
  D7: [notes['D4'], notes['F#4'], notes['A4'], notes['C5']],
  D7sus4: [notes['D4'], notes['G4'], notes['A4'], notes['C5']],

  Ebmaj: [notes['Eb4'], notes['G4'], notes['Bb4']],
  Ebmin: [notes['Eb4'], notes['Gb4'], notes['Bb4']],
  Ebdim: [notes['Eb4'], notes['Gb4'], notes['A4']],
  Ebaug: [notes['Eb4'], notes['G4'], notes['B4']],
  Ebmaj7: [notes['Eb4'], notes['G4'], notes['Bb4'], notes['D5']],
  Ebmin7: [notes['Eb4'], notes['Gb4'], notes['Bb4'], notes['Db5']],
  Eb7: [notes['Eb4'], notes['G4'], notes['Bb4'], notes['Db5']],
  Eb7sus4: [notes['Eb4'], notes['Ab4'], notes['Bb4'], notes['Db5']],

  Emaj: [notes['E4'], notes['G#4'], notes['B4']],
  Emin: [notes['E4'], notes['G4'], notes['B4']],
  Edim: [notes['E4'], notes['G4'], notes['Bb4']],
  Eaug: [notes['E4'], notes['G#4'], notes['C5']],
  Emaj7: [notes['E4'], notes['G#4'], notes['B4'], notes['D#5']],
  Emin7: [notes['E4'], notes['G4'], notes['B4'], notes['D5']],
  E7: [notes['E4'], notes['G#4'], notes['B4'], notes['D5']],
  E7sus4: [notes['E4'], notes['A4'], notes['B4'], notes['D5']],

  Fmaj: [notes['F4'], notes['A4'], notes['C5']],
  Fmin: [notes['F4'], notes['Ab4'], notes['C5']],
  Fdim: [notes['F4'], notes['Ab4'], notes['B4']],
  Faug: [notes['F4'], notes['A4'], notes['C#5']],
  Fmaj7: [notes['F4'], notes['A4'], notes['C5'], notes['E5']],
  Fmin7: [notes['F4'], notes['Ab4'], notes['C5'], notes['Eb5']],
  F7: [notes['F4'], notes['A4'], notes['C5'], notes['Eb5']],
  F7sus4: [notes['F4'], notes['Bb4'], notes['C5'], notes['Eb5']],

  'F#maj': [notes['F#4'], notes['A#4'], notes['C#5']],
  'F#min': [notes['F#4'], notes['A4'], notes['C#5']],
  'F#dim': [notes['F#4'], notes['A4'], notes['C5']],
  'F#aug': [notes['F#4'], notes['A#4'], notes['D5']],
  'F#maj7': [notes['F#4'], notes['A#4'], notes['C#5'], notes['F5']],
  'F#min7': [notes['F#4'], notes['A4'], notes['C#5'], notes['E5']],
  'F#7': [notes['F#4'], notes['A#4'], notes['C#5'], notes['E5']],
  'F#7sus4': [notes['F#4'], notes['B4'], notes['C#5'], notes['E5']],

  Gmaj: [notes['G4'], notes['B4'], notes['D5']],
  Gmin: [notes['G4'], notes['Bb4'], notes['D5']],
  Gdim: [notes['G4'], notes['Bb4'], notes['Db5']],
  Gaug: [notes['G4'], notes['B4'], notes['D#5']],
  Gmaj7: [notes['G4'], notes['B4'], notes['D5'], notes['F#5']],
  Gmin7: [notes['G4'], notes['Bb4'], notes['D5'], notes['F5']],
  G7: [notes['G4'], notes['B4'], notes['D5'], notes['F5']],
  G7sus4: [notes['G4'], notes['C5'], notes['D5'], notes['F5']]
} as const
