name: Pull request checks
on: pull_request
jobs:
  pr-check:
    name: PR Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm i
      - run: pnpm run lint
      - run: pnpm run format:check
